### PR TITLE
Watch Complications

### PR DESCRIPTION
**Pull request by bassrock**
Work in progress PR to add a base watch app and Watch complications using WidgetKit in watchOS 9.0 with the existing widget code.

Open to @creepymonster's feedback before I go further!

Screenshot 2022-12-31 at 11 12 42 PM
Screenshot 2022-12-31 at 11 12 48 PM

### CODE REVIEW

**Comment by creepymonster** [comment]
Wow, thanks a lot - I really like the display on the Apple Watch.

I'm not a Watch user myself - is the refresh budget for the Apple Watch similarly restrictive as for the widgets?

That's why the detour via a calendar was often taken.

**Comment by bassrock** [comment]
@creepymonster I'm not sure exactly, but it probably is since it is WidgetKit under the hood. I do like the calendar approach too, this just looked fun and not to bad to add.

Note that because I decided to re-use the WidgetKit code instead of the old school complications, this will be watchOS 9+ only.

**Comment by creepymonster** [comment]
Thank you very much, I will integrate it as well.

I like the possibility that the values can be displayed easily and intuitively on the Apple Watch.

Possibly it is also just as desired that you get "every now and then" times an update of the blood glucose on the clock.

So (in contrast to the regular calendar updates) perhaps some energy is saved. Through the alarms you are informed when the blood sugar develops negatively. Moreover, it can be quite sufficient how often the Apple Watch updates itself.

**Comment by philippkanter** [comment]
Hi guys. Can you give a rough estimate when we can expect the watch complications to be available in a release version? I know you guys do this in your free time, so don't feel rushed. I'm just curios. (Also the calendar workaround drains the battery quite a bit.)

**Comment by creepymonster** [comment]
Hello,

I was first overwhelmed with the first PR with changes to the project file and have therefore now started to integrate the commits in a separate build.

I would like to publish the Watch App Complication in the next release.

Reimar

**Comment by asiergmorato** [comment]
I would love to be able to use GlucoseDirect directly on the watch so I can leave my phone behind when I workout.
https://hturan.com/writing/apple-watch-continuous-glucose-monitoring

**Comment by gui-dos** [comment]
@asiergmorato:

SwiftUI lets you write independent Apple Watch apps sharing most of the base code with the iOS/Catalyst counterparts,  i. e. Core Bluetooth. Impossible for xDrip4iO5 but feasible for GD still, I think.

I am not managing correctly the background sessions but with my [DiaBLE](https://github.com/gui-dos/DiaBLE) I succeeded in detecting the Libre 3 thanks to its advertised data service and scraping directly the LibreLinkUp one-minute data:

incoming-EB1580FE-F44E-4279-9431-8DCE145A436C

**Comment by bassrock** [comment]
closing for #506

**Pull request closed without merging**
